### Home Page
GET http://localhost:3000/

###---------------------------------------
###  --> Register,Login 
###---------------------------------------

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "name" : "johndoe",
   "email": "johndoe@test.com",
   "password": "password"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "johndoe@test.com",
   "password": "password"
}

###------------------------------------------------------
### --> GET http://localhost:3000/index/<_Index_Name_> 
###------------------------------------------------------

### BSE Data
GET http://localhost:3000/index/bse

### NSE Data
GET http://localhost:3000/index/nse

### Companies Data : Ashok-Leyland 
GET http://localhost:3000/index/ashokley  

### Companies Data : Cipla
GET http://localhost:3000/index/ashokley  



